# Generated by Django 2.2 on 2019-07-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahnuapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=1000)),
                ('publish', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('url_link', models.CharField(max_length=10000)),
            ],
        ),
    ]
