from django.urls import path, include
from . import views

urlpatterns = [
    path('index/', views.index, name='index'),
    path('teachers/', views.teachers, name='teachers'),
    path('achievement_1/', views.achievement_1, name='achievement_1'),
    path('achievement_2/', views.achievement_2, name='achievement_2'),
    path('achievement_3/', views.achievement_3, name='achievement_3'),
    path('achievement_4/', views.achievement_4, name='achievement_4'),
    path('achievement_5/', views.achievement_5, name='achievement_5'),
    path('achievement_6/', views.achievement_6, name='achievement_6'),
    path('achievement_7/', views.achievement_7, name='achievement_7'),
    path('achievement_8/', views.achievement_8, name='achievement_8'),
    path('achievement_9/', views.achievement_9, name='achievement_9'),
    path('achievement_10/', views.achievement_10, name='achievement_10'),
    path('achievement_11/', views.achievement_11, name='achievement_11'),
    path('achievement_12/', views.achievement_12, name='achievement_12'),
    path('achievement_13/', views.achievement_13, name='achievement_13'),
    path('achievement_14/', views.achievement_14, name='achievement_14'),
    path('achievement_15/', views.achievement_15, name='achievement_15'),
    path('achievement_16/', views.achievement_16, name='achievement_16'),
    path('achievement_17/', views.achievement_17, name='achievement_17'),
    path('achievement_18/', views.achievement_18, name='achievement_18'),
    path('achievement_19/', views.achievement_19, name='achievement_19'),
    path('achievement_20/', views.achievement_20, name='achievement_20'),
    path('achievement_21/', views.achievement_21, name='achievement_21'),
    path('achievement_22/', views.achievement_22, name='achievement_22'),
    path('achievement_23/', views.achievement_23, name='achievement_23'),
    path('achievement_24/', views.achievement_24, name='achievement_24'),
    path('achievement_25/', views.achievement_25, name='achievement_25'),
    path('user_logout/', views.user_logout, name='user_logout'),
]